package com.compomics.peptizer.gui.component;

import com.compomics.peptizer.gui.PeptizerGUI;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * This class is a
 */
public class MainIconPanel {
    private JButton btnSaveTask;
    private JButton btnNewTask;
    private JToggleButton btnInfo;
    private JPanel jpanContent;
    private PeptizerGUI iPeptizerGUI;

    /**
     * Constructs a panel has a series of application wide functions.
     */
    public MainIconPanel(PeptizerGUI aPeptizerGUI) {
        iPeptizerGUI = aPeptizerGUI;

        // Start new task.
        btnNewTask.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent aActionEvent) {
                iPeptizerGUI.newTask();
            }
        });
        btnNewTask.setToolTipText("New peptizer task");

        // Save Current task.
        btnSaveTask.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent aActionEvent) {
                iPeptizerGUI.saveTask();
            }
        });
        btnSaveTask.setToolTipText("Save peptizer task");

        btnInfo.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent aActionEvent) {
                iPeptizerGUI.toggleInfoPanel();
            }
        });
        btnInfo.setToolTipText("Toggle logging information");

        EmptyBorder lBorder = new EmptyBorder(0, 0, 0, 0);

        btnInfo.setBorder(lBorder);
        btnNewTask.setBorder(lBorder);
        btnSaveTask.setBorder(lBorder);

    }


    private void createUIComponents() {
        // TODO: place custom component creation code here
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        jpanContent = new JPanel();
        jpanContent.setLayout(new FormLayout("fill:50px:noGrow,left:4dlu:noGrow,fill:50px:noGrow,left:4dlu:noGrow,fill:50px:noGrow", "center:10px:noGrow,top:3dlu:noGrow,center:d:noGrow"));
        btnNewTask = new JButton();
        btnNewTask.setIcon(new ImageIcon(getClass().getResource("/image/ICON_newtask.png")));
        btnNewTask.setText("");
        CellConstraints cc = new CellConstraints();
        jpanContent.add(btnNewTask, cc.xy(1, 3));
        btnSaveTask = new JButton();
        btnSaveTask.setEnabled(true);
        btnSaveTask.setIcon(new ImageIcon(getClass().getResource("/image/ICON_save_project.png")));
        btnSaveTask.setText("");
        jpanContent.add(btnSaveTask, cc.xy(3, 3));
        btnInfo = new JToggleButton();
        btnInfo.setHideActionText(true);
        btnInfo.setIcon(new ImageIcon(getClass().getResource("/image/ICON_log.png")));
        btnInfo.setText("");
        jpanContent.add(btnInfo, cc.xy(5, 3));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return jpanContent;
    }
}
